[workspace]
authors = ["Luis A. Lopez Atencio <luisangellopezatencio@outlook.com>"]
channels = ["conda-forge"]
name = "ImageRecognizer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
pydantic-core = ">=2.39.0, <3"
annotated-types = ">=0.7.0, <0.8"
anyio = ">=4.10.0, <5"
certifi = ">=2025.8.3, <2026"
charset-normalizer = ">=3.4.3, <4"
click = ">=8.2.1, <9"
colorama = ">=0.4.6, <0.5"
fastapi = ">=0.116.1, <0.117"
filelock = ">=3.19.1, <4"
h11 = ">=0.16.0, <0.17"
httpcore = ">=1.0.9, <2"
httpx = ">=0.28.1, <0.29"
idna = ">=3.10, <4"
iniconfig = ">=2.1.0, <3"
jinja2 = ">=3.1.6, <4"
markupsafe = ">=3.0.2, <4"
mpmath = ">=1.3.0, <2"
networkx = ">=3.5, <4"
numpy = ">=2.3.2, <3"
packaging = ">=25.0, <26"
pillow = ">=11.3.0, <12"
pluggy = ">=1.6.0, <2"
pydantic = ">=1.10.22, <2"
pytest = ">=8.4.1, <9"
python-multipart = ">=0.0.20, <0.0.21"
requests = ">=2.32.5, <3"
sniffio = ">=1.3.1, <2"
starlette = ">=0.47.3, <0.48"
sympy = ">=1.14.0, <2"
torch = ">=2.8.0, <3"
torchvision = ">=0.23.0, <0.24"
typing-extensions = ">=4.15.0, <5"
urllib3 = ">=2.5.0, <3"
uvicorn = ">=0.35.0, <0.36"
